### PR TITLE
add custom permission to call TermuxService from external apps

### PR DESCRIPTION
**Pull request by edaubert**
This pull request is an attempt to provide a solution to https://github.com/termux/termux-app/issues/804

### CODE REVIEW

**Comment by EpicOrange** [comment]
Just curious, does this mean that apps with this permission effectively have access to `/data/data/com.termux`?

**Comment by edaubert** [comment]
No you don't have access to it.

You need to use some storage permission I guess.
I guess another possibility could be to send the file to termux before trying to execute it.

**Comment by edaubert** [comment]
Yet another way to do it is to give storage access to termux and store the script where it can find it.

https://wiki.termux.com/wiki/Termux-setup-storage

**Comment by edaubert** [comment]
So I have completed a termux plugin on Easer which fully use the permission.
It uses the fact that termux provide a document provider. This provider allow external apps to get access to some files inside the termux environment.

Please have a look here: https://github.com/renyuneyun/Easer/pull/205

**Comment by fornwall** [comment]
We discussed this in a chat session (https://gitter.im/termux/dev) today, and I think this is a really interesting thing to have. Some notes from the chat:

The thing we want to minimise is the risk for evil apps to infect Termux installations (due to people ignoring/not understanding what the permission does). A conservative change could be to make this some kind of opt in, like requiring a property in termux.properties for this to be allowed
so we both require that permission, but we also need something like external-apps-can-execute=*, or external-apps-can-execute=com.app1,com.app2.

Or it could be a runtime permission. Perhaps a dialog like "The app XXX is trying to run a script. Allow that?" with a checkbox to remember the choice though that obviously complicates the code and also the user experience. Thoughts on that?

@xeffyr: A dialog like "The app XXX is trying to run a script. Allow that?" with a checkbox to remember the choice seems better than termux.properties.

@fornwall What I can't decide on is if that is necessary :). One point is that the app is a terminal emulator, users should be expected to a bit more technically skilled than an average app users and careful with accepting permissions.

... On the other hand, if the effect of opening up permissions is that several users have e.g. their ssh/gpg private keys stolen or likewise, it's bad regardless of if those users can be blamed for not reading through permissions.

Feedback, thoughts and ideas are welcome here! Even with the above said I'm leaning against merging this as is.

**Comment by edaubert** [comment]
As @fornwall said, I am not sure we need to add an extra layer of security.

First as it is said the users of termux are expected to be advanced users and so, in my opinion, should be aware of what implies to accept a permission. Well for me even non advanced users should be aware of this...

Second, it is the termux app which defines the permission and so the description can be explicit. And if a user do not want to read the permission dialog why should he want to read yet another popup dialog.

About the part of "their ssh/gpg private keys stolen or likewise, it's bad regardless of if those users can be blamed for not reading through permissions" you completly right but if the user gives root access to another app, it can also stole its data and termux is not able to protect those data even without speaking of permission. In the end, and this is mostly my really subjective opinion 😃, users are still responsible of what happens and permissions are something which is not just a bother which display annoying dialog.

However, if you are still willing something, i will propose to add a notification with multiple actions.
The notification provide a small text about running a script (name of the script and who ask to run it)
- action 1: always run it
- action 2: run it once
- actiin 3: never run it

Why I am proposing a notification is because I don't want to be interrupted by something that I may have not ask for (e.g. an automation script).
Plus if people do not care about popup dialog, they may care about their notifications.

But again for me, this is only an extra layer of security for supposed advanced termux users and I think they do not need that.

**Comment by ujeropoc** [comment]
little late too the party, but what about outsourcing this to another app?:  #1048

**Comment by xeffyr** [comment]
@ujeropoc Executing commands via URLs is weird solution from security side. It just won't be possible to use Android permissions here.

**Comment by MisterY** [comment]
What @edaubert suggests, with a dialog that resembles SuperSu's or through a notification,  is handy. But it would also be good to able to pre-configure the permissions before running because, as was mentioned, the point is to run automated and we may not know in advance when this will happen.
On the pragmatic side, would it be possible to come up even with a partial implementation, perhaps in a test version, which implements at least a rudimentary version of authorization, so that we can try it out and provide feedback? That way we could iron-out any issues that happen during actual use.
I'd like to create an app that provides a GUI for entering transactions and utilizes Ledger in the background to list the accounts defined by the user. Ledger is available as a binary package and can be run on the command line.
Thanks for all the great work so far.

**Comment by Ciantic** [comment]
I don't think this needs extra layer of security either, termux is for developers mostly anyway. Having just blanket permission is just fine. If you want extra security, you could restrict it to e.g. folder:

```~/appscripts/*```

So that apps are allowed to run scripts only from appscripts folder.

**Comment by xalexalex** [comment]
I also agree with the fact that having a working version (whose security can later be improved) is better than not having this functionality at all.

**Comment by RoninNada** [comment]
Would someone be able to provide an example of this being implemented/used? Sending a command an executing from another from another app? I already built a version of termux with this implemented just can't get the other part to work. I want it to work off a button press. Thank You

**Comment by xeffyr** [comment]
@RoninNada Make sure that application implements Termux service call in the way like:
``` .java
// scriptUri is URI path to script file.
Intent executeIntent = new Intent("com.termux.service_execute", scriptUri);
executeIntent.setClassName("com.termux", "com.termux.app.TermuxService");

// Whether to execute script in background.
//executeIntent.putExtra("com.termux.execute.background", true);
```
Service access permission must be granted to that "another application" in order to make code above work.

**Comment by RoninNada** [comment]
@xeffyr , thank you so much really helpful

**Comment by Ciantic** [comment]
I'm trying to understand the pushes above, was this merged? Is it now possible to call shell apps from within other apps?

**Comment by xeffyr** [comment]
It isn't merged and current implementation available here won't be merged. With @fornwall we agreed to:

* Do not let applications to access TermuxService directly.
* Implement separate service for calling with external applications (`TermuxServiceForExternalApps`).
* TermuxServiceForExternalApps will do necessary checks (e.g. property `allow-external-apps` is enabled).

**Comment by bdovaz** [comment]
@xeffyr How is that going?

**Comment by soso-cloud** [comment]
Want to know these account password
https://www.facebook.com/myamya.shein.75

**Comment by xeffyr** [comment]
Implemented in https://github.com/termux/termux-app/commit/db3ff7b24a2cb8c84b00cc5cec083361018569a1.

**Comment by bdovaz** [comment]
@xeffyr I just saw the commit:

https://github.com/termux/termux-app/commit/db3ff7b24a2cb8c84b00cc5cec083361018569a1

But how can I retrieve the command output? In my case I need that and I don't see an example.

Thanks.

**Comment by xeffyr** [comment]
> But how can I retrieve the command output? In my case I need that and I don't see an example.

This isn't possible with intents. Here you just start an activity or service with specific parameters.

**Comment by bdovaz** [comment]
@xeffyr but is there any way to achieve what I want? Thanks.

**Comment by ZhaoTzuHsien** [comment]
When will this important improvement be released? :)

**Comment by xeffyr** [comment]
@ZhaoTzuHsien It is already released by https://github.com/termux/termux-app/commit/db3ff7b24a2cb8c84b00cc5cec083361018569a1 in application version **0.95**.

**Comment by bdovaz** [comment]
@xeffyr you didn't answer my last question. Is there any way to achieve that? Or will it be possible? Or at least, can I read some file where the output it's being written so I can pool it? Thanks.

**Comment by xeffyr** [comment]
>Is there any way to achieve that? Or will it be possible?

Will be possible as soon as *someone* will write an api engine for that, with IPC, proper permission checks, etc.

**Comment by agnostic-apollo** [comment]
@xeffyr can the `EXTRA_EXECUTE_IN_BACKGROUND` also be received when the `com.termux.RUN_COMMAND` action intent is processed and passed to the `TermuxService`. It would make it easier to run background commands like with Tasker. Basically show the notification but not the session activity unless user manually opens it if required. There seems to be reasonable security for it to be an issue. Thanks

**Comment by agnostic-apollo** [comment]
@xeffyr it seems that the RUN_COMMAND_ARGUMENTS is not working. You are receiving and sending it as a string extra in [RunCommandService](https://github.com/termux/termux-app/blob/51370799c765d1774abac61a6f2eedf09156d211/app/src/main/java/com/termux/app/RunCommandService.java#L55) but receiving it as a string array extra in [TermuxService](https://github.com/termux/termux-app/blob/51370799c765d1774abac61a6f2eedf09156d211/app/src/main/java/com/termux/app/TermuxService.java#L147) resulting it in being ignored as far as I can see. A simple `sleep 5` commands shows `sleep: missing arguments`. 

You probably have your own test app but leaving following instructions for others:

The `com.termux.permission.RUN_COMMAND` has been added to the Tasker `AnndroidManifest.xml` in the list of requested permissions in [v5.9.3.rc](https://www.reddit.com/r/tasker/comments/i0253r/dev_tasker_593rc_getting_ready_for_public_release/). It should automatically be requested when `TermuxCommand` function is used in a `Tasker Function` action or you can grant it manually from something like Tasker app permissions -> Additional permissions -> `Run commands in termux environment`, specially if you intend to run am shell commands instead. When you run a command or script in the function or use am command, a new termux session will open up and run the command. It will automatically close by default when the command completes. You can put the session in background mode if you want after that. However, starting it in background mode is not supported and has been [requested](https://github.com/termux/termux-app/pull/1029#issuecomment-649715644) requested.

After you grant the permission, you also need to add the `allow-external-apps=true` property in `~/.termux/termux.properties` file for intents to be allowed. You can run the following command in a non-root termux session to add the line to the end of the file if it doesn't exist already.

```
cd ~ && mkdir -p .termux && grep -sq  "allow-external-apps=true" ./.termux/termux.properties || echo $'\n'"allow-external-apps=true" >> ./.termux/termux.properties
```

After that you can run the command with a `Tasker Funtion` action or am command using a `Run Shell` action. The arguments and working directory are optional. An example am command would be something like the following.
```
am startservice --user 0 -n com.termux/com.termux.app.RunCommandService -a com.termux.RUN_COMMAND --es com.termux.RUN_COMMAND_PATH "/data/data/com.termux/files/usr/bin/top" --es com.termux.RUN_COMMAND_ARGUMENTS "-n 5" --es com.termux.RUN_COMMAND_WORKDIR "/data/data/com.termux/files/home"
```

**Comment by xeffyr** [comment]
> You are receiving and sending it as a string extra in RunCommandService but receiving it as a string array extra in TermuxService resulting it in being ignored as far as I can see. A simple sleep 5 commands shows sleep: missing arguments. Do you want a pull request?

Ok, that's a bug. You can submit a pull request to fix it.

**Comment by agnostic-apollo** [comment]
Should I also include support for passing the background flag as well or not?

**Comment by xeffyr** [comment]
Yes.

**Comment by agnostic-apollo** [comment]
Okay thank. I will do it and let you know.

**Comment by agnostic-apollo** [comment]
I have added a pull request [here](https://github.com/termux/termux-app/pull/1679). Let me know if any changes need to be made. I also updated the docs a bit, I hope that's all right.

**Comment by minhdanhsc** [comment]
Can I run the command from another application to termux? Who has a sample for my reference?

**Comment by xeffyr** [comment]
@minhdanhsc https://github.com/termux/termux-app/blob/master/app/src/main/java/com/termux/app/RunCommandService.java#L23-L62

**Pull request closed without merging**
