### PR TITLE
Allow installing Termux on the SD card

### PR DESCRIPTION
**Pull request by brunoais**

### CODE REVIEW

**Comment by brunoais** [comment]
@kcubeterm Why closing? Is this not feasible for this app?

**Comment by agnostic-apollo** [comment]
This will not allow storage of termux app data like `$HOME` and `$PREFIX` on the external removable sd card, it will just allow installation of APK on external storage.

>The .apk file is saved on the external storage, but all private user data, databases, optimized .dex files, and extracted native code are saved on the internal device memory.

https://developer.android.com/guide/topics/data/install-location

Moreover, check [Applications that should NOT install on external storage](https://developer.android.com/guide/topics/data/install-location#ShouldNot) section. This will cause problems with termux service, boot receiver, widgets, etc. Saving ~80MB (which may reduce to ~20MB in future) is not worth all the mess this will create.

**Comment by brunoais** [comment]
I see... Thank you for explaining.

**Comment by agnostic-apollo** [comment]
welcome.

**Pull request closed without merging**
