### PR TITLE
Fix for #1262

### PR DESCRIPTION
**Pull request by xeffyr**
Fix for issue described in https://github.com/termux/termux-app/issues/1262.

### CODE REVIEW

**Comment by fornwall** [comment]
As we discussed, this means we only send the "button press" event, and never the "button release" event. So this should cause issues such as the text selection in micro to be triggered a lot more, right?

**Comment by xeffyr** [comment]
> text selection in micro to be triggered a lot more

For me it fixes behaviour described in https://github.com/termux/termux-app/issues/1262 completely I do not experience selection triggering a lot more.

We discussed about sending "mouse button pressed" event in `onDown()` and "mouse button released" event in `onUp()`. However the function `onDown()` has a different signature and doesn't receive MotionEvent like in `onUp()`.

**Comment by fornwall** [comment]
in the `onUp()` event we send two mouse events directly - mouse pressed and mouse released.

The byte sequence sent to the terminal from Termux, in the SGR scheme mostly used by programs now, should look like this:

```
0033  27 0x1B Escape '^[' or '\e'
0133  91 0x5B ASCII '['
0074  60 0x3C ASCII '<'
0060  48 0x30 ASCII '0'
0073  59 0x3B ASCII ';'
0065  53 0x35 ASCII '5'
0063  51 0x33 ASCII '3'
0073  59 0x3B ASCII ';'
0062  50 0x32 ASCII '2'
0061  49 0x31 ASCII '1'
0115  77 0x4D ASCII 'M'

0033  27 0x1B Escape '^[' or '\e'
0133  91 0x5B ASCII '['
0074  60 0x3C ASCII '<'
0060  48 0x30 ASCII '0'
0073  59 0x3B ASCII ';'
0065  53 0x35 ASCII '5'
0063  51 0x33 ASCII '3'
0073  59 0x3B ASCII ';'
0062  50 0x32 ASCII '2'
0061  49 0x31 ASCII '1'
0155 109 0x6D ASCII 'm'
```
where the format is (https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Mouse-Tracking):

```
SGR (1006)
          The normal mouse response is altered to use
          -   CSI < followed by semicolon-separated
          -   encoded button value,
          -   Px and Py ordinates and
          -   a final character which is M  for button press and m for button release.
```

This can be seen by executing `vtshowkeys -m` and touching the terminal.

Under tmux however, what the program (vtshowkeys) sees is often `m` (button release) coming before `M` (button press) - it seems that tmux (sometimes/quite often) reverses the order of these events. I don't know why that is.

**Comment by fornwall** [comment]
@xeffyr At least the text selection issue of micro under tmux is fixed after updating to version `2.9a-5` of tmux, right?

**Comment by xeffyr** [comment]
Well, that explains why issue was reproducible only under `tmux`. I'm closing pull request as latest update fixed it.

**Pull request closed without merging**
