### PR TITLE
Fixed: Remove from recent apps on app close

### PR DESCRIPTION
**Pull request by Rillian-Grant**
This change removes finished terminal sessions from the recent apps view.

### CODE REVIEW

**Comment by agnostic-apollo** [comment]
Reasonable, but that will need to be added as a `termux.properties` property since not everyone would want that. Default should be `false`.

https://github.com/termux/termux-app/blob/master/termux-shared/src/main/java/com/termux/shared/termux/settings/properties/TermuxPropertyConstants.java

**Comment by Rillian-Grant** [comment]
I've added it. Could you check my placement of it it the settings menu along with the text.

**Comment by Rillian-Grant** [comment]
While working on this I noticed that the app exits with finishAndRemoveTask if the back button is pressed. Should this be the case as pressing the back button is a less extreme exit than the terminal itself exiting?

Apologies for the large screenshot.

**Comment by agnostic-apollo** [comment]
You have added it in preferences, not in properties like mentioned above. Termux user settings must all go in `termux.properties` so that they can be backed up easily by users, unless they are critical and accessing them with `termux,properties` would be an issue if something breaks or shouldn't be backed up.

>Should this be the case as pressing the back button is a less extreme exit than the terminal itself exiting?

You should check with `TermuxService` if any sessions remain before calling `finishAndRemoveTask()`.

**Comment by Rillian-Grant** [comment]
I've added it to properties and undone the other changes.
Can you advise on how to add the option commented out to the default termux.properties file?

At present, the back button calls finishAndRemoveTask no matter how many sessions remain. This seems wrong.  Some better options are:
 - Exiting the app with no effect on running sessions and staying in recent apps.
 - Closing the current session or if none remains exit and remove from recent apps.
But this looks like a separate issue, I'll create a separate issue and pull request.

**Comment by RalfWerner** [comment]
>A key like `remove-termux-activity-from-recents-on-exit` should be fine.
### What happens when it set?
Current state in the screenshot below, the _recent processes_ are on the left. Termux was finished here and also to the right where a SSH session on the same device that was also ended after the `ps` process was displayed. The notifications are no longer included, which remains the case when an SSH session is started again.
It is only back when the _recent **Termux** session_ is activated again. In the notifications, Termux can be closed with **exit**, but this maintains the process status and the _recent processes_.
grafik
Except 2842 and 4737 all other processes have ended only when the _recent **Termux** process_ is removed. If Termux is then started again (first [OTS](https://github.com/termux/termux-float/issues/37#issuecomment-916777123)=5411+2842+8786+8793), this is no longer possible without ending Termux-X11 via the notification.
Removing the _recent **Termux-X11** process_ (like for Termux) is here **insufficient!**

**Comment by agnostic-apollo** [comment]
>I've added it to properties and undone the other changes.

The key variable name and function name must match the key name.

> Can you advise on how to add the option commented out to the default termux.properties file?

That goes in https://github.com/termux/termux-tools/blob/master/termux.properties

>This seems wrong.

Following should likely work from a quick look. There might be other cases as well that may need to be looked into.

```
if (mProperties.isRemoveTermuxActivityFromRecentsOnExitEnabled() && mTermuxService != null && mTermuxService.isTermuxSessionsEmpty())
	finishAndRemoveTask();
else
	finish();
```

>But this looks like a separate issue, I'll create a separate issue and pull request.

It is not a separate issue, you created the issue in this pull request with the feature add and any issues should be fixed here and feature properly implemented before it can be merged.

And there should be no merge commits in pull requests.

**Comment by RalfWerner** [comment]
@sylirre, @agnostic-apollo related to our discussion about _"process-killing"_ yesterday: 

My Samsung (SM-P610) _android 12 update_ was done yesterday (15 minutes see [dev](https://gitter.im/termux/dev?at=62ffce499994996293e51c01)). After that I started Termux (with OTS=14820-15468) and pid4=nedit=20623 (DISPLAY on PC). Then I created an `ssh` process (32078) from the PC to SM-P610 and started PID4=`touch.exe` (DISPLAY=: 0).

The **good news:** All OTS processes still exist after 12 hours. The **bad news:** all other processes (20623+32078+touch) were killed`*1`. I then restarted them (12968+12874+13405).
Here are the associated Termux outputs (the first after update to Android 12) on SM-P610 with process check yesterday:
```
Report issues at https://termux.dev/issues # <--- last line from modt
Version:'0.118/12=29 target=28 aarch64 192.168.0.118 WM=
moin Xwayland:, Xvnc: sshd: :0
Starting: Intent { cmp=com.termux.x11/.MainActivity }
Start:0:Xwayland=15468 try 1
Starting: Intent { cmp=com.termux/.app.TermuxActivity }
Warning: Activity not started, its current task has been brought to the front
  PID  PPID COMMAND             ELAPSED
14820  4753 com.termux            00:09
15015 14820 bash                  00:07
15167     1 sshd                  00:06
15276  4753 com.termux.x11        00:05
15466 15015 bash                  00:03
15468 15466 Xwayland              00:03
15587 15015 ps                    00:01
alias ll='ls -la'
alias lt='ls -haltogL'
alias n='u uu n i/touch.c i/check.c /home/.termux/termux.properties &'
alias pp='ps -eo pid,ppid,comm,etime'
alias t='bash .bashrc'
alias u='bash uu.sh'
[~]$ n
[2] 20623
[~]$ c=nedit -display 192.168.0.115:0 i/bashrc /home/uu.sh/n i/touch.c i/check.c /home/.termux/termux.properties
Terminated
[~]$ pp
#process check today
  PID  PPID COMMAND             ELAPSED
12874 15167 sshd                  30:25
12878 12874 bash                  30:23
12962 12878 bash                  27:10
12965 12962 proot                 27:10
12967 12965 sh                    27:10
12968 12967 nedit                 27:10
13361 12878 bash                  17:23
13405 13361 touch.exe             17:21
14820  4753 com.termux         11:52:36
15015 14820 bash               11:52:34
15167     1 sshd               11:52:33
15276  4753 com.termux.x11     11:52:32
15466 15015 bash               11:52:30
15468 15466 Xwayland           11:52:30
23382 15015 ps                    00:01
```
`*1` is not new in sdk31 and maybe related to WiFi or PC-sleeping-mode (I was sleeping too).
Following Termux output on PC (`ssh`=12843)
```
#process check yesterday(ssh on PC)  process check today
[~]$ pp                              [~]$ n
  PID  PPID COMMAND         ELAPSED  [1] 12962
14820  4753 com.termux     02:00:06  [~]$ c=nedit -display 192.168.0.115:0 i/bashrc /home/uu.sh/n i/touch.c i/check.c /home/.termux/termux.properties
14966 32080 ps                00:01  pp
15015 14820 bash           02:00:04    PID  PPID COMMAND         ELAPSED
15167     1 sshd           02:00:03  12874 15167 sshd              03:45
15276  4753 com.termux.x11 02:00:02  12878 12874 bash              03:43
15466 15015 bash           02:00:00  12962 12878 bash              00:30
15468 15466 Xwayland       02:00:00  12965 12962 proot             00:30
32078 15167 sshd           01:40:02  12967 12965 sh                00:30
32080 32078 bash           01:39:59  12968 12967 nedit             00:30
32158 32080 bash           01:38:44  12976 12878 ps                00:01
32161 32158 proot          01:38:43  14820  4753 com.termux     11:25:56
32163 32161 sh             01:38:43  15015 14820 bash           11:25:54
32164 32163 nedit          01:38:43  15167     1 sshd           11:25:53
[~]$ termux-battery-status           15276  4753 com.termux.x11 11:25:52
{                                    15466 15015 bash           11:25:50
  "health": "GOOD",                  15468 15466 Xwayland       11:25:50
  "percentage": 100,
  "plugged": "PLUGGED_USB",
  "status": "FULL",
  "temperature": 26.5,
  "current": 0
Connection reset by 192.168.0.118
```
Unfortunately, I cannot repeat the [Shot](https://user-images.githubusercontent.com/45426380/185401070-7fef34dd-633d-4cde-9a8c-90613d9ea446.png) from the commit [above](https://github.com/termux/termux-app/pull/2941#issuecomment-1219495151). It was from the `ssh` session **and** of an SM-P610 `scrcpy` mirroring (both on PC). It fails on `scrcpy` that no longer works after the _update_ (setup is more complex than before).
I know this is not _Termux-related_ but maybe you can find something in the following error report:
```
D:\Android\scrcpy\scrcpy-server: 1 file pushed, 0 skipped. 11.5 MB/s (33142 bytes in 0.003s)
[server] INFO: Device: samsung SM-P610 (Android 12)
INFO: Created renderer: direct3d
INFO: Renderer: direct3d
INFO: Initial texture: 2000x1200
ERROR: SDL failed to get a vertex buffer for this Direct3D 9 rendering batch!
ERROR: Dropping back to a slower method.
ERROR: This might be a brief hiccup, but if performance is bad, this is probably why.
ERROR: This error will not be logged again for this renderer.
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
        at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:75)
        at com.genymobile.scrcpy.ScreenEncoder.setDisplaySurface(ScreenEncoder.java:216)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:86)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:55)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:76)
        at com.genymobile.scrcpy.Server.main(Server.java:225)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:374)
Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:73)
        ... 7 more
Caused by: java.lang.IllegalArgumentException: displayToken must not be null
        at android.view.SurfaceControl$Transaction.setDisplaySurface(SurfaceControl.java:3370)
        at android.view.SurfaceControl.setDisplaySurface(SurfaceControl.java:2344)
        ... 9 more
Press any key to continue...
```
If I choose USB standard, I only get **one** error: `[server] Error: Exception on thread thread [main, 5, main]`

**Comment by nomeata** [comment]
I just noticed that syncthing has added code to remove it from recent tasks upon exit, which made me happy. The other “persistentish” app where I always have to manually kill it from the recent tasks list to avoid accidentally restarting it is termux, so I came to suggest the same. Glad someone is already working on it! Much appreciated. @Rillian-Grant, are you going to see this through code review?

**Pull request closed without merging**
