### PR TITLE
Fix Termux crash on malformed config file

### PR DESCRIPTION
**Pull request by koppa**
When having an malformed json input in the extra-keys property, the termux-app crashes later with an NullpointerException due to an uninitialized mExtraKeys variable.

This fix improves the parsing of the properties file. In case of an invalid "extra-keys" property, the variable will be initialized with length 0.

### CODE REVIEW

**Comment by Grimler91** [comment]
Great, we most certainly need more verification :)

I also see that you've added an alternative config path (just mentioning it since it's worth mentioning)

**Comment by koppa** [comment]
> I also see that you've added an alternative config path (just mentioning it since it's worth mentioning)

Nope, that wasn't me, this is already in master.

I just splitted the try-catch clause into two parts: One for IOException handling and the other for parsing the JSON of extra-keys

**Comment by Grimler91** [comment]
> Nope, that wasn't me, this is already in master.

Ah sorry, I blame my small phone screen. 
Anyways, great!

**Comment by fornwall** [comment]
Thanks!

**Pull request merged**
