### PR TITLE
Updating manifest to support resizeableActivity

### PR DESCRIPTION
**Pull request by twoboxen**
Updating manifest to support resizeableActivity for main app and help screen. 

[This is also used by Samsung's DeX mode.](http://developer.samsung.com/samsung-dex/modify-optimizing)

### CODE REVIEW

**Comment by pp3345** [comment]
This should not make any difference as resizeableActivity defaults to true already.

**Comment by twoboxen** [comment]
Why doesn't it work on dex already then?

**Comment by fornwall** [comment]
As @pp3345 says this attribute should already default to true:

    If your app targets API level 24, but you do not specify a value for this attribute, the attribute's value defaults to true.

From https://developer.android.com/guide/topics/ui/multi-window.html.

So dex problems should come from something else.

**Comment by zhunsaker** [comment]
question 3 samsung developer guide


Your app might have targeting the wrong targetSDKVersion. Android:resizeableActivity is supported when the targetSDK version is greater than or equal to 24 (Android N). IF targetSDKVesion is under 24, activities are only resizable when the screenOrientation is not set as fixed. Check to make sure you do not have this code in your manifest: 

<activity android:screenOrientation="portrait | landscape"> </activity>

**Comment by fornwall** [comment]
@twoboxen Sorry about this - you were right in that it was resizeableActivity="true" which was needed. I still don't understand why it is needed as it should be the default value when the target API is 24+ (could it be a Samsung bug perhaps), but anyway it works now.

**Comment by twoboxen** [comment]
Hey no worries.  I'm just glad you got it working!

Thanks!!

**Pull request closed without merging**
