### PR TITLE
replace help url with wiki url

### PR DESCRIPTION
**Pull request by Auxilus**
HELP page wiki changed to https://wiki.termux.com/wiki/Main_Page as it now has more info than http://termux.com/help.html

### CODE REVIEW

**Comment by sdrausty** [comment]
@auxilus I don't think this pull request is a great idea. 

1. Anyone can change the help on the wiki. What if someone mucks up the wiki help. That will find its' way in the app immediately. 

2. We can always improve the help pages through pulls to https://github.com/termux/termux.github.io/blob/master/help.md and similar. 

What if someone spams the help pages on the wiki? Or changes the help pages maliciously? How useful will that be?

**Comment by Auxilus** [comment]
As long as @Neo-Oli is actively monitoring the wiki changes, we are good.. Afaik wiki.termux.com has more content than help page on termux.com. Also I think @fornwall is okay with considering wiki.termux.com as official wiki

PS: open editing is what makes wiki more informative, also you'll need active moderation team to keep track of it..

**Comment by sdrausty** [comment]
The correct way would be to modify https://github.com/termux/termux.github.io/blob/master/help.md where help is secure, not on a wiki. Can you please show me a successful major project where the help inside the app is hosted on a wiki? Let the wiki be complementary help. Why eliminate the good help pages we have?

**Comment by sdrausty** [comment]
Adding a wiki link to https://github.com/termux/termux.github.io/blob/master/help.md is a suggestion. Help on long press from github - link to wiki in the help pages would be OK.

**Comment by sdrausty** [comment]
Imho wiki.termux.com should be hosted at http://pages.github.com

1. No spam. 
2. User accountability. 
3. Practicing simple pull requests. 
4. ETC

We have enough content to do this.

**Comment by Neo-Oli** [comment]
> Can you please show me a successful major project where the help inside the app is hosted on a wiki?
Both Archlinux and LineageOS only have a wiki as their primary documentation.

**Comment by Neo-Oli** [comment]
> Imho wiki.termux.com should be hosted at http://pages.github.com

That's exactly what the help pages were. There were almost no contributions made for years.

**Comment by sdrausty** [comment]
@Neo-Oli These are not apps. Are the man and info pages on a wiki too.

**Comment by Neo-Oli** [comment]
> Are the man and info pages for these OSes on a wiki too?

The man and info pages for Termux are also not on a wiki.

**Comment by sdrausty** [comment]
@Neo-Oli >That's exactly what the help pages were. There were almost no contributions made for years.
Great. Lets add a few links to them then. The wiki should be complementary, nor overriding.

**Comment by sdrausty** [comment]
Anyone can change the help on the wiki. What if someone mucks up the wiki help. That will find its' way into the app immediately. Link to wiki pages from the help pages is my suggestion, i.e. 👉 See Also

**Comment by sdrausty** [comment]
I can see this temptation already. Someone adds rm -rf $PREFIX noob to long press help in our app.

**Comment by sdrausty** [comment]
Or, long press help in Termux, and out pops, "Get Viagra HTTPS Link" or something similar. Temptation for many spammers and equivalent.

**Comment by fornwall** [comment]
I currently think that the wiki is the way forward, and that the advantages of having information that can be easily updated and contributed to outweighs the risks.

Let's try it out, if there is a serious problem we can always switch back or to something else.

**Comment by Auxilus** [comment]
As I mentioned earlier if we switch help link to wiki.termux.com, we must have active moderation team to monitor the changes as site traffic would be increased.

**Pull request merged**
