### PR TITLE
Termux as a downloader #446

### PR DESCRIPTION
**Pull request by sayem314**
This would add feature requested on issue #446., user need to have termux-url-opener for proper usage tho!

### CODE REVIEW

**Comment by sayem314** [comment]
@fbartels 8 months for approving changes! Seriously? 😞

**Comment by fbartels** [comment]
Not that my approval does mean that @fornwall will merge it anytime soon, but I would like to see this feature as well (just stumbled upon this today).

**Comment by sayem314** [comment]
Ah I see. Thanks 🙏

**Comment by justworks007** [comment]
Please this feature would be amazing.

**Comment by buttaface** [comment]
Interesting, @fornwall would have to decide this.

**Comment by wqzq** [comment]
@xeffyr would you take a look at this please.

**Comment by buttaface** [comment]
Even if this got in, it would not be deployed to most users in the Play store, as [the app there is no longer updated](https://wiki.termux.com/wiki/Termux_Google_Play). If you use F-Droid, it would be updated.

@fornwall should approve this because I think he has intentionally kept permissions minimal so far.

**Pull request merged**
