### PR TITLE
Added java.io export to gradle.properties to fix app not compiling on latest gradle versions

### PR DESCRIPTION
**Pull request by richard-hgs**
This will fix the error on andorid studio latest versions

"Unable to make field private final java.lang.String java.io.File.path accessible:
 Unable to make field private final java.lang.String java.io.File.path
 accessible: module java.base does not "opens java.io" to unnamed module @42760a00"

### CODE REVIEW

**Comment by agnostic-apollo** [comment]
Which JDK and gradle version are you using?

**Comment by ED4free** [comment]
Hi @richard-hgs, I am a beginner with Android Studio, can you please tell me which line to add in which gradle file ?
I have the same error : "Unable to make field private final java.lang.String java.io.File.path accessible: module java.base does not "opens java.io" to unnamed module @8ee186"  when I build termux-app dowloaded from 
Thanks a lot.
Thierry

**Comment by tareksander** [comment]
@ED4free 

Had the same issue, I updated AGP and Gradle to [this](https://github.com/tareksander/termux-app/commit/7ea61ee3dc1858f186d0581b423d1d58d6da5ef9).

**Comment by ED4free** [comment]
Thanks a lot @tareksander , it works !

**Comment by tomaszduda23** [comment]
https://github.com/fluttercommunity/flutter_workmanager/issues/287#issuecomment-893476072 it also solve the problem

**Comment by fornwall** [comment]
Thanks! Closing this in favour of https://github.com/termux/termux-app/pull/3619.

**Pull request closed without merging**
