### PR TITLE
Changed: New launcher shortcut icons

### PR DESCRIPTION
**Pull request by TermuxMonet**
Added some new icons to termux shortcut menu on launchers.

Preview:
Screenshot_20220712-100109_POCO Launcher~01

### CODE REVIEW

**Review by NoorImann — COMMENTED** [review]
me@server

**Comment by DevMoxxie** [comment]
> me@server

?

**Comment by agnostic-apollo** [comment]
Possibly a bot, banned for 7 days.

**Comment by HardcodedCat** [comment]
Requires #2875 in order to work

**Pull request closed without merging**
