### PR TITLE
Remove intent category "default" from manifest

### PR DESCRIPTION
**Pull request by xeffyr**
* Intent category "default" is not needed after dropping failsafe icon.

* Also move the routines to clear /tmp dir to TermuxService.onDestroy().

### CODE REVIEW

**Comment by tomty89** [comment]
@xeffyr

Should `TMPDIR` clean up be performed after `stopForeground()`?

Also, can you make it clean its canonical file instead so that it also works when e.g. `PREFIX` is a symlink?

@fornwall

What's the point of the `finishIfRunning` loops? It wouldn't kill the non-shell processes anyway.

Also, in the two ocassions where `stopSelf()` is called conditionally, one checks whether there's any background task while one does not, why is that? (In other words, why shouldn't `removeTermSession()` just call `updateNotification()` unconditionally?)

In addition, why should `stopSelf()` be called unconditionally for `ACTION_STOP_SERVICE`? (especially when `onDestroy()` doesn't deal with background tasks)

**Comment by xeffyr** [comment]
> Should TMPDIR clean up be performed after stopForeground()?

Is there some benefits in doing it after `stopForeground()` ?

> Also, can you make it clean its canonical file instead so that it also works when e.g. PREFIX is a symlink?

Yes, will do.

**Comment by fornwall** [comment]
This is being part of the v0.71 which is now rolling out on Google Play.

**Comment by tomty89** [comment]
@xeffyr I just thought perhaps `stopForeground()` is responsible for killing all the processes.

**Comment by xeffyr** [comment]
> stopForeground() is responsible for killing all the processes.

It just removes Service from foreground state. It doesn't kill any processes.

**Pull request merged**
