### PR TITLE
Changed: New repo description design

### PR DESCRIPTION
**Pull request by TermuxMonet**
Added some better badges to the description, center alignment using html, a screenshot from the app and a termux logo. 
The logo uses a Open Source font called Lexend.

### CODE REVIEW

**Comment by Grimler91** [comment]
The screenshot seem to be from a very old app version, urls are outdated. It also seems unnecessary to include the android keyboard in it. Maybe a screenshot from a (landscape) tablet would have a form-factor more suited for most screens

**Comment by Grimler91** [comment]
And please follow commit message style, see [git history](https://github.com/termux/termux-app/commits/master)

**Comment by DevMoxxie** [comment]
Marked as draft until the decision of new motd design to avoid divergent screenshots.

**Comment by DevMoxxie** [comment]
Both 

> And please follow commit message style, see [git history](https://github.com/termux/termux-app/commits/master)

Your both reviews were attended 👍

**Comment by gascs** [comment]
All I can say is that this change of yours is a piece of shit, why change the original language to adopt a new one, is your brain run over by a car?

**Comment by gascs** [comment]
All I can say is that your changes and your creativity are a piece of shit, shit, this change is very unreasonable!

**Comment by agnostic-apollo** [comment]
@gascs You will get banned for being abusive.

**Comment by gascs** [comment]
Whoops, can't I go and post my dissatisfied comments?  Is this your official face?

**Comment by gascs** [comment]
Can't I express my own views with your changes?

**Comment by gascs** [comment]
Funny, this is how you handle it?

**Comment by gascs** [comment]
> @gascs You will get banned for being abusive.

All I can say is that this change of yours is very unreasonable, and you don't allow others to point out your mistakes?  Do not allow others to spur?

**Comment by Grimler91** [comment]
@gascs feel free to learn some manners and get back with constructive feedback rather than just insults

**Comment by WMCBTech** [comment]
I think its worth noting that some people would prefer the classic motd while this new implementation is something new that old termuxistas wouldn't get used to.

We've seen some reports regarding this. perhaps we could poll this out? while this change is pretty quite aestethic for some. I think the plain one is suited for me, secondly is zoom issues which this breaks the motd readability if there's not enough columns to print.

**Comment by agnostic-apollo** [comment]
@WMCBTech Check https://github.com/termux/termux-packages/pull/11250#issuecomment-1203850944

**Comment by HardcodedCat** [comment]
### Done some changes to the PR.

 - Now the logo color changes with GitHub's light and dark mode
 - Fixed badges according to https://github.com/badges/shields/issues/8671

**Pull request closed without merging**
