### PR TITLE
chore: changed "Twitter" to "X (Twitter)" In README.md Important Links Section

### PR DESCRIPTION
**Pull request by BandhiyaHardik**
Changed! : changed "Twitter" to "X (Twitter)"

This Fixes https://github.com/termux/termux-app/issues/3680

### CODE REVIEW

**Comment by agnostic-apollo** [comment]
The `𝕏` ([`U+1D54F`](https://www.compart.com/en/unicode/U+1D54F)) unicode character does not seem to be the official logo for twitter as far as I see, it has only been referred as similar to it. I don't see it on the their [logos page](https://about.twitter.com/en/who-we-are/brand-toolkit) and their official channel [@X](https://twitter.com/X) is also using a simple `X` alphabet.

Use `X` instead and also follow commit guidelines.

https://github.com/termux/termux-app#for-maintainers-and-contributors

**Comment by BandhiyaHardik** [comment]
@agnostic-apollo  i will change it as per commit guidelines

**Comment by agnostic-apollo** [comment]
You have not followed the guidelines, I have also updated them to be more clear. It needs to be ```Changed: Update `Twitter` to `X (Twitter)` in README```. You also have multiple commits, squash them.

**Comment by BandhiyaHardik** [comment]
I will do it today.

**Comment by BandhiyaHardik** [comment]
Sorry there is a bit mistake with the commit message i will change it

**Comment by agnostic-apollo** [comment]
Your commit message is now set to

```
 Changed: Update Twitter to X (Twitter) in README

Changed: Update `Twitter` to `𝕏 (Twitter)` in README

Changed: Update `Twitter` to `X (Twitter)` in README

Changed: Update `Twitter` to `X (Twitter)` in README

Changed: Update `Twitter` to `X (Twitter)` in README
```

And you are now making other changes to the README file, likely since your branch hasn't been rebased against `master` branch. Do a hard git reset to an older commit, rebase against master and make commit again. After your next try, will do it myself.

**Comment by BandhiyaHardik** [comment]
@agnostic-apollo i have exams going on right now so if it's alright with you can you resolve this issue? 

I will close my PR.

**Comment by agnostic-apollo** [comment]
Okay

**Comment by BandhiyaHardik** [comment]
@agnostic-apollo i have exams going on right now so if it's alright with you can you resolve this issue? 

I will close my PR.

**Comment by agnostic-apollo** [comment]
Done in 3b5018b4c79a2c2d218eb6fd570b2f2bebb8415a

Welcome.

**Pull request closed without merging**
