### PR TITLE
Update AndroidManifest.xml

### PR DESCRIPTION
**Pull request by CanKolay5677**
*DELETE THIS SHIT CODE*

### CODE REVIEW

**Comment by agnostic-apollo** [comment]
Its not "SHIT CODE". It tells android what type of files can `TermuxFileReceiverActivity` handle.

Check https://developer.android.com/guide/components/intents-filters#Building

**Comment by CanKolay5677** [comment]
...

https://cdn.discordapp.com/attachments/641257795005710338/848877315445620756/2021_05_31_13_54_11.mp4

**Comment by agnostic-apollo** [comment]
Check [here](https://github.com/termux/termux-app/issues/1905#issuecomment-842647559).

**Comment by LeapofAzzam-backup** [comment]
Why

**Comment by LeapofAzzam-backup** [comment]
Or just make it */*

**Comment by agnostic-apollo** [comment]
>Or just make it `*/*`

That will match every type of file and will show termux in share menu for them all.

**Pull request closed without merging**
