### PR TITLE
Changed!: Bump Robolectric to 4.9.2

### PR DESCRIPTION
**Pull request by utzcoz**

### CODE REVIEW

**Comment by utzcoz** [comment]
Hi @agnostic-apollo  @Grimler91 , could you help to give a review to this PR? Thanks.

**Comment by agnostic-apollo** [comment]
Use `Changed` type in commit message, otherwise is fine.

https://github.com/termux/termux-app#for-maintainers-and-contributors

**Comment by utzcoz** [comment]
@agnostic-apollo Thanks. I added `Changed!:` to the commit message.

**Comment by utzcoz** [comment]
Friendly ping @agnostic-apollo for reviewing.

**Comment by agnostic-apollo** [comment]
Thanks.

Bumping roboelectric version is not a breaking change, so `!` should not be added. And in future, do not use merge commits to sync with `master`, learn to use `rebase`.

https://matrix.to/#/!rrHhKvLYtBVDOISphu:gitter.im/$rloCNAUzgDa2pSVbT_FK5QPMME2njQ3do9KCONET2S4?via=gitter.im&via=t2bot.io&via=matrix.org

**Comment by utzcoz** [comment]
@agnostic-apollo Thanks.  I will take attention to these rules next time.

**Pull request merged**
