### PR TITLE
add some func keys

### LINKED ISSUE #571: Add arrow keys
Hi there, 

It will be very useful to have arrow keys in Termux similar to [TWRP]( https://twrp.me)'s terminal.
Thanks.

screenshot_2018-02-04-00-05-18

### PR DESCRIPTION
**Pull request by xqdoo00o**
Just like JuiceSSH, more convenient. For example, long press `arrow key` to continuous input arrows, slip up `/` key to input `\`. Also fix #571 or #12 .
screenshot

### CODE REVIEW

**Comment by FuckDoctors** [comment]
good job～

**Comment by sdrausty** [comment]
Looks nice 👷

**Comment by decke** [comment]
Thanks a lot!

**Comment by robertvandeneynde** [comment]
Awesome !

Where did the "|" go ? I don't say it's mandatory but it was included in the keys for a reason : pipe in bash.

Furthermore, shouldn't it be configurable in some settings ? "No extra keys, one line, two lines... One line but these keys : 1, 2, 3..."

**Comment by sdrausty** [comment]
> Where did the "|" go ? 

Ditto.  Can any of these keys popup?  Say for example the / on long tap becomes a -, /, and |.

> configurable

Configurable keyboard, sounds nice.  What about the configuration menu @robertvandeneynde?

**Comment by robertvandeneynde** [comment]
I don't see any configuration menu in my app, I can only long press on the screen to have a menu that has _Help_ that is showing me the _Termux wiki_ having a bit of tutorials like _User Interface, how to use this app_.

Maybe that's kind of hidden somewhere (like the "Swipe from left side of screen to center" menu) which by the way is not a good advantage of having _hidden_ menus. Even the "extra keys" is _hidden_ (long press on a button if a _hidden_ menu ?).

On the other side, configuration is great if it's easy to find how to do it, but having good defaults is important too.

**Comment by sdrausty** [comment]
@xqdoo00o the | pipe should remain on top as it is used often in shells for piping.  Otherwise it is hidden deep in the keyboard.  Would it be difficult for you to add long press popup.  

With the popup feature this could become one row with more keys:

| ESC        | \|           | 🔼  | PGUP |
| ------------- |:-------------:| -----:| ---:|
| TAB      | / | ◀ | HOME |
| CTRL      | \      |   ▶ | END |
| ALT | -      |    🔽 |  PGDN |

Ten columns can fit in the top row.  Just like the number keys do.  The example above shows a 4x4 matrix.  Now a 10x2 matrix would yield many more keys than we have at present.  For example:

| ESC        |  TAB           | 🔼  | 🔽 | PGUP | PGDN |  \| | / | CTR | ALT |
| ------------- |:-------------:| -----:| ---:| ---:| ---:| ---:| ---:| ---:| --:|
| 🔧 | 🔧 | ◀ | ▶ | HOME | END | - | \ | 🔧 | 🔧 |
| 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 0 |

**Comment by sdrausty** [comment]
@robertvandeneynde there are four spots to customize any character you desire, two on the left, and two on the right in this layout.  Think popout one row menu.  On the other hand, the entire second row could popout tools to o.

**Comment by robertvandeneynde** [comment]
The :wrench: symbols would mean _custom symbol in here_, that's an idea indeed. An another idea would be to _insert_ characters via a configuration menu somewhere, insert of replacing it.

But what were you talking about _What about the configuration menu_ ?

But if we were to talk about your 10×2 layout, I'd prefer the arrow keys being in a natural position (like a keyboard) as in the screenshot of @xqdoo00o, same for Home/End and PageUp/Down.

**Comment by xqdoo00o** [comment]
@robertvandeneynde @sdrausty currently, the longpress action means writing key on session continuously except for `CTRL` and `ALT`.
May the action just for `arrow keys`? that's more common usage.
Then the other button could a longpress popup.

**Comment by robertvandeneynde** [comment]
Clearly long press giving key repeat is a great feature (**especially** for arrow keys), I didn't know this feature !

I was not not talking about any long press on a key, what are you talking about ?

**Comment by xqdoo00o** [comment]
ok, I add some popups. Currently, for "-" it's "|", for "/" it's "\\".

**Comment by robertvandeneynde** [comment]
People using "|" a lot might complain. What about adding some settings ?

One could choose between :
- No extra keys
- One line of extra keys : Esc Ctrl Alt Tab - / |
- Two lines : your proposal
- Custom

If implementing a settings menu is a big deal, the current way of doing it (long press on the Keyboard button in the left hidden menu) could cycle through the 3 first settings.

For me, your popup that's good enough... If I'm aware I can long press your keys to get new characters (which is not obvious, could be written in the wiki).

Lastly, what about [this comment](https://github.com/termux/termux-app/pull/605#pullrequestreview-101019511) ?

**Comment by xqdoo00o** [comment]
@robertvandeneynde The code you said is here [origin code](https://github.com/termux/termux-app/blob/master/app/src/main/java/com/termux/app/ExtraKeysView.java#L53). It has been removed in this PR.

**Comment by robertvandeneynde** [comment]
Good, slipup is better than long press indeed. For the '― -' issue, I asked _why did you remove '―', it was more visible than '-'_ but that's just cosmetics, not so important :)

**Comment by xqdoo00o** [comment]
@robertvandeneynde  I know your means. and a commit comes.

**Comment by robertvandeneynde** [comment]
How could this PR be accepted by the authors ? Or a least discuessed ? It seems like the repo didn't have any commit sinice 1 month but is a long requested feature in the issues @fornwall maybe ? :) I intend to use termux as a ipython for my classes at the university if the app suits my need ? :)

**Comment by Deathlive** [comment]
How to enable these keys?

**Comment by Neo-Oli** [comment]
@Deathlive https://wiki.termux.com/wiki/Touch_Keyboard#Extra_Keys_Row

**Comment by Deathlive** [comment]
@Neo-Oli Volume Up+Q includes this
screenshot_1
But how then to include this?
screensho5

**Comment by Neo-Oli** [comment]
@Deathlive This Pull request hasn't been merged yet, so it isn't available.

**Comment by xqdoo00o** [comment]
@Deathlive Here is the apk I built ago. 
try `wget https://ipfs.io/ipfs/QmXCsQ89u6M9DPXvQHVGoS4BXnrkyZU8PWUxnPXf1jBswQ -O release.apk`

**Comment by fornwall** [comment]
@xqdoo00o Awesome work and sorry for the delay! This will be available in the next update (v0.62) shortly!

**Comment by powerjc** [comment]
@xqdoo00o Thank you! Did a double take today to make sure I was in the right app. I'd been unwittingly using the new keys for ten minutes. Loving them.

**Comment by johnny-mac** [comment]
but how do you get that menu??? Its not coming up for me, I have the latest version of the app -.-

**Comment by johnny-mac** [comment]
How will I use vi without insert? :/

**Comment by Neo-Oli** [comment]
> How will I use vi without insert? :/

`i`

**Comment by remo7777** [comment]
> @Neo-Oli Volume Up+Q includes this
> screenshot_1
> But how then to include this?
> screensho5

can we switch between 1-row and 2-row extra-key without delete termux.properties ?

**Comment by robertvandeneynde** [comment]
That's a feature we're working on soon :)

There will be a button "switch layout" you can personize, so that you can switch layouts for example between "terminal one line", useful for vim, or python focus :)

**Comment by Harshiv-Patel** [comment]
Need this layout on Android Lollipop 5.1.1, current version has only one row.

**Comment by Quasic** [comment]
@Harshiv-Patel, the default changed. See https://wiki.termux.com/wiki/Touch_Keyboard#Extra_Keys_Row for directions to customize it.

**Pull request merged**
