### PR TITLE
Changed: Bump Robolectric to 4.10

### PR DESCRIPTION
**Pull request by utzcoz**
See https://github.com/robolectric/robolectric/releases/tag/robolectric-4.10.

### CODE REVIEW

**Comment by utzcoz** [comment]
Friendly ping @agnostic-apollo for reviewing.

**Comment by agnostic-apollo** [comment]
Thanks robolectric-dependabot! Our one test dependent on it appreciates it. ;)

**Comment by utzcoz** [comment]
@agnostic-apollo Thanks for reviewing. Oh, you found out who I am. :)

**Comment by agnostic-apollo** [comment]
You are very welcome. lolz, yeah, I was curious why you were sending just pulls for robolectric updates. ;)

**Comment by agnostic-apollo** [comment]
Ah, cool. More tests are planned for future so robolectric would hopefully be of more use and would then require keeping up to date with updates even more and so would probably require our robolectric-dependabot.

That's great. Hopefully, termux has been treating you nice.

**Comment by agnostic-apollo** [comment]
Yeah, will look into writing more tests when `termux-shared` library is split. Currently, I only write on-device tests for critical or security related stuff like filesystem, unfortunately have limited time to write tests. Thanks for the offer, will surely keep it in mind :)

**Pull request merged**
