### PR TITLE
Changed: Updated FileReceiverActivityTest to include empty & null strings for invalidUrls to cover corner cases

### PR DESCRIPTION
**Pull request by jasonjyu**
Added to FileReceiverActivityTest empty & null strings for invalidUrls to cover corner cases

### CODE REVIEW

**Comment by jasonjyu** [comment]
@agnostic-apollo, @fornwall, would you have some time to review my PR?  Thanks.

**Comment by agnostic-apollo** [comment]
Fix commit message.

https://github.com/termux/termux-app#commit-messages-guidelines

**Comment by jasonjyu** [comment]
> Fix commit message.
> 
> https://github.com/termux/termux-app#commit-messages-guidelines

Can do.

**Comment by jasonjyu** [comment]
@agnostic-apollo, does my latest commit message conform to the guidelines now?

**Comment by jasonjyu** [comment]
> Fix commit message.
> 
> https://github.com/termux/termux-app#commit-messages-guidelines

I fixed my commit message.  Thanks.

**Comment by agnostic-apollo** [comment]
Did you not bother running the tests to see if they actually passed?

**Pull request merged**
