### PR TITLE
0.118: bump bootstraps to v2024.06.09-r1

### PR DESCRIPTION
**Pull request by Grimler91**
Installation and pkg/apt usage, and general use, works fine on both arm and aarch64

### CODE REVIEW

**Comment by Grimler91** [comment]
Running tests from https://github.com/termux/termux-exec/pull/24 succeeds if I remove --ld-preload arg and just install and use libtermux-exec.so from $PREFIX/lib/ instead, that is I apply:

```diff
diff --git a/Makefile b/Makefile
index afc3d63..cf5769e 100644
--- a/Makefile
+++ b/Makefile
@@ -178,7 +178,7 @@ deb: all
 
 test: all
        $(MAKE) TERMUX_EXEC__INSTALL_PREFIX=install install
-       tests/termux-exec-tests --ld-preload="install/lib/libtermux-exec.so" --tests-path="install/libexec/installed-tests/termux-exec" -vvv all
+       tests/termux-exec-tests --tests-path="install/libexec/installed-tests/termux-exec" -vvv all
 
 test-unit: all
        $(MAKE) TERMUX_EXEC__INSTALL_PREFIX=install install
@@ -186,7 +186,7 @@ test-unit: all
 
 test-runtime: all
        $(MAKE) TERMUX_EXEC__INSTALL_PREFIX=install install
-       tests/termux-exec-tests --ld-preload="install/lib/libtermux-exec.so" --tests-path="install/libexec/installed-tests/termux-exec" -vvv runtime
+       tests/termux-exec-tests --tests-path="install/libexec/installed-tests/termux-exec" -vvv runtime
 
 
 

```

haven't tested with termux-api and termux-am, but otherwise all tests succeed on both arm and aarch64
[arm.log](https://github.com/user-attachments/files/15754146/arm.log)
[aarch64.log](https://github.com/user-attachments/files/15754147/aarch64.log)

**Comment by fornwall** [comment]
Ok to merge and tag a `0.118.1` release?

Would be nice to get it out to fix the issue of people being prompted for updating away from F-Droid to Google Play. See also https://github.com/termux/termux-app/issues/4012#issuecomment-2164762685 - a systematic version code scheme can come later perhaps.

**Comment by Grimler91** [comment]
I think @agnostic-apollo mentioned that it would be good to cherry-pick some additional fixes/improvements from master before tagging a release, for example workflows so that apk's are built and uploaded to the new release

**Comment by agnostic-apollo** [comment]
Workflow is broken in master branch too, I fixed it in my local `master` branch a while back and have also fixed it in my new local release branch.

**Comment by agnostic-apollo** [comment]
@Grimler91 Found the reason for `make test` failing after exporting `TERMUX_EXEC__LOG_LEVEL=4`.

```
Termux.exec: Failed to access executable path '/data/data/com.termux/files/usr/libexec/installed-tests/termux-exec/files/exec/print-args-binary': No such file or directory 
```

Even though the test files path was passed to `termux-exec-tests` with `--tests-path` to the `install` sub directory under source directory, the  `runtime-binary-tests.c` was using hardcoded (macro) tests paths under `$PREFIX/libexexec/*` and then failed to find the paths. I have fixed it by making it check the `TERMUX_EXEC__TESTS_PATH` env variable to see if its set (with fallback to macro) and dynamically generating the test file paths.

Another error was that `LD_PRELOAD` being passed with `--ld-preload` wasn't converted to an absolute path, which then failed due to linking error for later `bash` tests.

**Comment by twaik** [comment]
Probably it will be a good idea to update release with newest bootstrap with same version but bumped versionCode, without making any new commits to release code. So both f-droid and github releases will have newest bootstrap even if the apk code was not changed.

**Pull request closed without merging**
