### PR TITLE
For android 6

### PR DESCRIPTION
**Pull request by NOTURFRIENDBTW**
Please make it work for android 6 dude i am so really need make games using godot on termux my phone so trash alright

### CODE REVIEW

**Comment by agnostic-apollo** [comment]
Termux is not supported on android 6 anymore. Packages cannot be maintained for old versions.

Install legacy versions of termux app. Note that packages will be outdated and will not be updated.

https://www.reddit.com/r/termux/comments/dnzdbs/end_of_android56_support_on_20200101/?utm_medium=android_app&utm_source=share

https://www.reddit.com/r/termux/comments/eoiics/trying_to_install_on_android_6/fed6gqq?utm_medium=android_app&utm_source=share&context=3

**Comment by NOTURFRIENDBTW** [comment]
Sadly i just need use proot-distro (only proot-distro)

**Comment by WMCB-Tech** [comment]
You can install the script, but you need to use `--no-sysvipc` option if launching distros

**Comment by NOTURFRIENDBTW** [comment]
> You can install the script (by git cloning the repo and running `install.sh` script,) but you need to use `--no-sysvipc` option if launching distros every time
> 
> https://github.com/termux/proot-distro

How do I install it? I'm too stupid for this

**Comment by NOTURFRIENDBTW** [comment]
Please answer :(

**Comment by WMCB-Tech** [comment]
Install proot-distro from git
```
pkg install proot
git clone https://github.com/termux/proot-distro
cd proot-distro
bash install.sh
```

When Launching Distro, you will need to append `--no-sysvipc` every time
```
proot-distro login <distro_name> --no-sysvipc
```

See `proot-distro help` for more information after installation

**Comment by NOTURFRIENDBTW** [comment]
Thanks its work

**Comment by WarmEpoch** [comment]
> Install proot-distro from git
> 
> ```
> pkg install proot
> git clone https://github.com/termux/proot-distro
> cd proot-distro
> bash install.sh
> ```
> 
> Some Tip: When Launching Distro, you will need to append `--no-sysvipc` every time if you have Android 5/6
> 
> ```
> proot-distro login <distro_name> --no-sysvipc
> ```
> 
> See `proot-distro help` for more information after installation

May I ask if you can still obtain the old version of the debian system from there

**Pull request closed without merging**
