### PR TITLE
maybe slightly improved

### PR DESCRIPTION
**Pull request by nitin-ojha1**
added link to f-droid and the apk, made it easy.

### CODE REVIEW

**Comment by agnostic-apollo** [comment]
I have no idea why you find "Termux application can be obtained from F-Droid from [here](https://f-droid.org/en/packages/com.termux/)" confusing or hard to find, specially considering its the first sentence of F-Droid installation section.

The [Contents](https://github.com/termux/termux-app#contents) at the top also have a link for Installation which you should refer to when reading any `README` of any project.

**Comment by SDRausty** [comment]
>have a link for Installation 

Can the APK be also released from 
https://github.com/termux/termux-app/releases?

**Comment by nitin-ojha1** [comment]
okay i guess ¯\_(ツ)_/¯

**Comment by agnostic-apollo** [comment]
>Can the APK be also released from
>https://github.com/termux/termux-app/releases?

I have thought about that, but that will requiring writing a custom workflow that periodically checks for updates on F-Droid and attaches it to releases (and keep track of already attached), since I would rather devs not download it locally to their devices before uploading. But then again, people might try to install it thinking its a `Github` debug build and get signature mismatch errors and then complain to us. Probably a separate repo should be created for all `F-Droid` releases till now.

**Comment by nitin-ojha1** [comment]
okay, that was just my opinion for a simplified version, cuz i was also facing some problems like others, it was hard to find links and important stuff. lol have a nice day

**Comment by SDRausty** [comment]
>Probably a separate repo should be created for all F-Droid releases

Sounds like a plan; +1

>debug build

Could it also include the debug build please?

>it was hard to find links and important stuff. 

Possibly this page https://wiki.termux.com/wiki/Installation wants improving;  You are welcome to help in improving the Termux wiki.

**Comment by nitin-ojha1** [comment]
> You are welcome to help and add important information to our Termux wiki.

okay i guess maybe

**Pull request closed without merging**
