### PR TITLE
Change double-tap and drag behavior from quick scale to mouse drag event

### PR DESCRIPTION
**Pull request by sunziping2016**
I've partly implemented the feature requested at [this issue](https://github.com/termux/termux-app/issues/35).

I think zoom with two finger pinching is already enough, so I change the reaction of double tap and drag from quick zoom to mouse left button drag event sending to emulator. It can help a lot e.g. under emacs, vim and tmux when you want to resize window or select text.

### CODE REVIEW

**Comment by sunziping2016** [comment]
Some bug fix.

**Comment by fornwall** [comment]
Thanks, will try this out after the next release of the app!

**Comment by TheDiamondYT1** [comment]
Should i make a bot to automatically bump PRs and Issues on the Termux github as they get forgotteb about

**Comment by sunziping2016** [comment]
I am really missing these features. And that's why I am still using my own build instead of the one on the Google Play.

**Comment by sunziping2016** [comment]
[Here](https://file.szp.io/f/60117f10ba/?dl=1) is a simple video demo for this feature.

**Comment by sunziping2016** [comment]
If you decide to merge my commit, maybe I can help to solve the conflicts and create another pull request for you.On Jun 15, 2017 11:47, EquinoxSTR4F3 <notifications@github.com> wrote:@EquinoxSTR4F3 commented on this pull request.

hi im new to this stuff, i wanna ask you a question, how do i apply this?

**Comment by jgallen23** [comment]
any chance this gets released? now that android apps can be installed on chromebooks, mouse input is going to be more prevalent

**Comment by sunziping2016** [comment]
@EquinoxSTR4F3 I've updated my commits to solve the conflicts. Now you can view the changes [here](https://github.com/termux/termux-app/pull/98/files) and confirm this pull request if you like.

**Comment by laosb** [comment]
ping ping any chance to merge

**Comment by tmatz** [comment]
What is preventing this important PR?

**Comment by bubnikv** [comment]
It may help to improve usability of the Samsung S-pen
https://github.com/termux/termux-app/issues/1744

**Review by vbifonixor — APPROVED** [review]

**Pull request closed without merging**
