### PR TITLE
Updated: Library, Gradle, NDK and Bootstrap updates

### PR DESCRIPTION
**Pull request by TermuxMonet**
Some users had some trouble with bootstrap packages, leading to apt failures, so i suggest keeping them updated.

Also i've included on this pull request some library, gradle and ndk updates.

### CODE REVIEW

**Comment by agnostic-apollo** [comment]
The `compileSdkVersion` and (some) google library versions cannot be updated without requiring other changes. Check https://github.com/termux/termux-app/commit/c59835ed9

> Some users had some trouble with bootstrap packages, leading to apt failures

I assume you are referring to kcubeterm repo issue. Those are for `v0.118.0` downloaded from F-Droid that's using bootstrap from january, issue wouldn't occur on bootstrap in `master` branch from april, although can be updated since its behind a couple of months now.

And follow contributing guidelines for commits.

https://github.com/termux/termux-app#for-maintainers-and-contributors

Gradle and ndk changes will need to be tested as well.

**Comment by DevMoxxie** [comment]
> The `compileSdkVersion` and (some) google library versions cannot be updated without requiring other changes. Check [c59835ed9](https://github.com/termux/termux-app/commit/c59835ed9)
> 
> > Some users had some trouble with bootstrap packages, leading to apt failures
> 
> I assume you are referring to kcubeterm repo issue. Those are for `v0.118.0` downloaded from F-Droid that's using bootstrap from january, issue wouldn't occur on bootstrap in `master` branch from april, although can be updated since its behind a couple of months now.
> 
> And follow contributing guidelines for commits.
> 
> https://github.com/termux/termux-app#for-maintainers-and-contributors
> 
> Gradle and ndk changes will need to be tested as well. Also the updated bootstrap on fresh installation and possibly compared against old version.

i've already tested the updated on old and fresh installation, using termux-monet. Everything worked, even with compileSdkVersion 31. but i'm not sure if that these changes would work on Android <12. that would need to be tested with older devices.

**Comment by HardcodedCat** [comment]
All the changes were successfully tested on Android 10, 9 and 7. Soon i'll test on Android 5

**Comment by agnostic-apollo** [comment]
Have you checked Jitpack and F-Droid incompatibility for bumping `compileSdkVersion` and fixes required?

**Comment by HardcodedCat** [comment]
> Have you checked Jitpack and F-Droid incompatibility for bumping `compileSdkVersion` and fixes required?

No fixed were required for bumping `compileSdkVersion`, and Jitpack workflow is successfully executed 

And i've tested on Android 5 some minutes ago, everything works

**Comment by HardcodedCat** [comment]
> Have you checked Jitpack and F-Droid incompatibility for bumping `compileSdkVersion` and fixes required?

But i don't have access to termux's jitpack and f-droid admin accounts to deploy anything and test, only fork's workflows

**Comment by agnostic-apollo** [comment]
Okay. Thanks. Will test myself and look into F-Droid as well.

**Pull request closed without merging**
