### PR TITLE
Add fast path for TerminalRow.setChar

### PR DESCRIPTION
**Pull request by michalbednarski**
Added fast path for TerminalRow.setChar for case where theres 1-to-1 mapping between characters and columns (that is no UTF-16 surrogate pairs and characters with width != 1)

Trying to fix termux/termux-app#603, please test @evg-zhabotinsky

In my tests this highly improved performance of `cat 500KBfile.txt` test.

Still slower than Android Terminal Emulator, but difference is now much smaller and seems to be matter of redraw throttling, without redrawing Termux is now faster (For test commented out line in [Termux](https://github.com/termux/termux-app/blob/9f36ed06b8e2c3b5e5918444e0c37699e21a7196/terminal-view/src/main/java/com/termux/view/TerminalView.java#L386) and [Android Terminal Emulator](https://github.com/jackpal/Android-Terminal-Emulator/blob/987e4eb56bb7bcb387a187ab78437111d327c984/emulatorview/src/main/java/jackpal/androidterm/emulatorview/EmulatorView.java#L488), press volume key in such version to redraw screen)

### CODE REVIEW

**Comment by evg-zhabotinsky** [comment]
Huh. So it was mostly paranoid unicode handling and not syncing?
Works fine for me, ~5MB file `cat`ing time is down to ~1.5 minutes from ~1 hour before the fix. `vim` also starts up instantly now. Could be faster, but at that point human is the bottleneck most of the time.

Still, it's a stopgap, and the other code path still needs to be optimized. Suggest keeping the issue open until then.

**Comment by fornwall** [comment]
@michalbednarski Sorry for the delay here! Looks interesting, nice gains without messing up the code.

I think `mHasNonOneWidthOrSurrogateChars` should be reset to false the `clear()` method, since otherwise over time all rows will end up having this set to true (as lines are reused after a while in the circular buffer).

**Comment by michalbednarski** [comment]
Rebased and added to flag reset to `clear`.

**Comment by fornwall** [comment]
Thanks! This will be in v0.62 of the app, to be released in a few days.

**Pull request merged**
