### PR TITLE
Delete RunCommandService.java

### PR DESCRIPTION
**Pull request by offsat**
02JZkYgAAAAD1BrkGMVR3RJYqpoXKJ4rNQk4zRURHRTExMTAANTk2ZDc4YTItY2E1Zi00NzlkLWJjZGMtMDgzNTgzMzE3NGIy

### CODE REVIEW

**Comment by offsat** [comment]
> _ No description provided. _

**Comment by offsat** [comment]
> > _ No description provided. _

**Comment by offsat** [comment]
02JZkYgAAAAD1BrkGMVR3RJYqpoXKJ4rNQk4zRURHRTExMTAANTk2ZDc4YTItY2E1Zi00NzlkLWJjZGMtMDgzNTgzMzE3NGIy

**Comment by offsat** [comment]
> 02JZkYgAAAAD1BrkGMVR3RJYqpoXKJ4rNQk4zRURHRTExMTAANTk2ZDc4YTItY2E1Zi00NzlkLWJjZGMtMDgzNTgzMzE3NGIy

**Comment by GitG33** [comment]
Greg Wayne Gonzales
COMPANY INFORMATIONCompany Name:  KING KONTRACTING LLCEntity
Type:  DOMESTIC LIMITED-LIABILITY COMPANYFile Number:  202126510723Filing
State:  California (CA)Filing Status:  ActiveFiling Date:  September 20,
2021Company Age:  5 MonthsRegistered Agent:  Northwest Registered Agent,
Inc.Principal Address:  2108 N St Ste N
Sacramento, CA 95816Mailing Address:  2108 N St Ste N
Sacramento, CA 95816Governing Agency:  California Secretary of StateCOMPANY
CONTACTS

**Comment by GitG33** [comment]
I do not see why you need to delete run command for this as it runs an
Android. It should run basically off your Linux applications you can run it
on your loan Chromebook are you can use Windows. The power terminal I'm not
sure what the right and Linguistics is for stating that but I know there's
a there's a power terminal that you can use in Windows is well. I apply to
your basic structures and and it should work fine. You can look back on
some of the the Repose that I have an emergency with the pull request also
I have an auto structure there somewhere they will auto-generate your SSL
Keys as well so you won't have to worry about regenerating or authorizing
or paying for any of it.

Greg Wayne Gonzales
COMPANY INFORMATIONCompany Name:  KING KONTRACTING LLCEntity
Type:  DOMESTIC LIMITED-LIABILITY COMPANYFile Number:  202126510723Filing
State:  California (CA)Filing Status:  ActiveFiling Date:  September 20,
2021Company Age:  5 MonthsRegistered Agent:  Northwest Registered Agent,
Inc.Principal Address:  2108 N St Ste N
Sacramento, CA 95816Mailing Address:  2108 N St Ste N
Sacramento, CA 95816Governing Agency:  California Secretary of StateCOMPANY
CONTACTS

**Comment by GitG33** [comment]
My JavaScript works fine I'm not sure what your dilemma or discrepancies
is. I've been running it through my Lennox Chromebook for a while and it
auto updates periodically all I have to do is just apply the app can update
it have get upgrades. As far as going back in restructuring I will have to
look further into my platforms and programming.

Greg Wayne Gonzales
COMPANY INFORMATIONCompany Name:  KING KONTRACTING LLCEntity
Type:  DOMESTIC LIMITED-LIABILITY COMPANYFile Number:  202126510723Filing
State:  California (CA)Filing Status:  ActiveFiling Date:  September 20,
2021Company Age:  5 MonthsRegistered Agent:  Northwest Registered Agent,
Inc.Principal Address:  2108 N St Ste N
Sacramento, CA 95816Mailing Address:  2108 N St Ste N
Sacramento, CA 95816Governing Agency:  California Secretary of StateCOMPANY
CONTACTS

**Comment by GitG33** [comment]
About the only time that I would have to use this marriage would be to hash
out any other kind of malicious ssl's are htmls. Further works and
processing will be analyzed when time is convenient.

Greg Wayne Gonzales
COMPANY INFORMATIONCompany Name:  KING KONTRACTING LLCEntity
Type:  DOMESTIC LIMITED-LIABILITY COMPANYFile Number:  202126510723Filing
State:  California (CA)Filing Status:  ActiveFiling Date:  September 20,
2021Company Age:  5 MonthsRegistered Agent:  Northwest Registered Agent,
Inc.Principal Address:  2108 N St Ste N
Sacramento, CA 95816Mailing Address:  2108 N St Ste N
Sacramento, CA 95816Governing Agency:  California Secretary of StateCOMPANY
CONTACTS

**Comment by wmcbtech30** [comment]
You are blocked for this organization for a long-term for disruptive content

**Pull request closed without merging**
