### PR TITLE
Deep Learning for Java

### PR DESCRIPTION
**Pull request by LobsterMan123**
Would you please make deep learning using Java possible on Termux?  Since Termux now has Java and Maven in the official package manager, this would be awesome. 
 There's a deep learning library for Java called "DL4J" that supposedly is able to run on Termux/arm processors but I've not been able to get it running on my Android device running Termux (the kind folks at DL4J have been trying to walk me through potential approaches but so far nothing's worked for me and I've thrown in the towel for now).  From what DL4J staff tell me, it seems that the challenge to getting DL4J to work on my device has something to do with the native dependencies (in C I believe).  Thanks.

### CODE REVIEW

**Comment by TomJo2000** [comment]
Forgive me for being blunt, but I don't see how this is at all relevant to the main Termux app.

Why do you wanna merge changes to 47 files, and 29 commits into this branch?

**Comment by LobsterMan123** [comment]
I'm so sorry!  I've never done a pull request before and I clicked on some buttons to initialize my pull request and I guess I clicked stuff I shouldn'tve which is why it's showing as such merging.  That was not my intention to ask for such drastic changes. My apologies.

I just wanted to submit my original question about getting DL4J suppirted by Termux, nothing else about 47 files or 29 commits.

**Comment by LobsterMan123** [comment]
Thanks TomJo2000 for the suggestion.  I just found the feature request section under "Issues" so I submitted it there not too long ago.

**Comment by TomJo2000** [comment]
I couldn't find any such feature request in my search.

**Comment by LobsterMan123** [comment]
I took a look at where it's showing up for me and it's listed as the first item at the URL below:

https://github.com/termux/termux-app/issues

**Pull request closed without merging**
